<div class="container">
	<div class="page-header">
		<h1>Dashboard <small><?php echo $title ?></small></h1>
	</div>

	<section>
		<ul>
			<?php foreach($goods as $key => $good): ?>
			<li>
				<div class="media">
					<div class="media-left">
						<a href="#">
							<img class="media-object" src="<?php echo $good->thumbnail ?>" width="64" alt="...">
						</a>
					</div>
					<div class="media-body">
						<h4 class="media-heading"><?php echo $good->name ?></h4>
						<p><?php echo $good->description ?><p>
					</div>
				</div>
			</li>
			<?php endforeach; ?>
		</ul>
	</section>
</div>