<!DOCTYPE html>
<html lang="pl">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo htmlspecialchars(implode(' - ', array_reverse($_config['title']))); ?></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="page-header">
				<h1>Logowanie</h1>
			</div>

			<form method="post" role="form" autocomplete="off" class="form-horizontal">
				<div class="form-group">
					<label class="control-label col-sm-4">Nazwa użytkownika</label>
					<div class="col-sm-8">
						<input type="text" name="username" placeholder="Nazwa użytkownika" class="form-control">
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-sm-4">Hasło</label>
					<div class="col-sm-8">
						<input type="password" name="password" placeholder="Hasło" class="form-control">
					</div>
				</div>

				<div class="form-group">
					<div class="col-sm-8 col-sm-offset-4">
						<div class="checkbox">
							<label>
								<input type="checkbox" name="remember" value="1" id="remember"> Zapamiętaj mnie
							</label>
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="col-sm-8 col-sm-offset-4">
						<input type="submit" name="button" value="Zaloguj się" class="btn btn-primary">
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

</body>
</html>