<?php
/**
 * Nadrzędna nawigacja, która wyświetlana jest w każdym szablonie.
 * Odseparowanie nawigacji pozwala na zastosowanie zasady DRY (Don't Repeat Yourself).
 * W nawigacji dostępna jest zmienna $settings z globalną konfiguracją systemu.
 */
?>
<nav class="navbar navbar-default navbar-inverse navbar-top-fixed">
	<div class="container">
		<div class="navbar-header">
			<a href="index.php" class="navbar-brand" title="Centrum Kontroli Lotów">
				<?php echo $site_title ?>
			</a>
		</div>

		<ul class="nav navbar-nav">
			<li class="dropdown">
				<a href="?controller=commodity" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
					Towary i usługi <span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="?controller=commodity">Przeglądaj towary</a></li>
					<li><a href="?controller=commodity&amp;action=add">Dodaj nowy towar</a></li>
					<li class="divider"></li>
					<li><a href="?controller=commodity&amp;action=search">Wyszukaj</a></li>
				</ul>
			</li>

			<li class="dropdown">
				<a href="?controller=analysis" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
					Analiza <span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="?controller=analysis&amp;action=find">Analiza towaru</a></li>
					<li><a href="?controller=analysis&amp;action=delivery">Wystawianie z dostawy</a></li>
					<li class="divider"></li>
					<li><a href="?controller=commodity&amp;action=agenda">Kalendarz (pełna analiza)</a></li>
				</ul>
			</li>
		</ul>

		<ul class="nav navbar-nav pull-right">
			<li>
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
					Piotr Filipek <span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#">Edytuj profil</a></li>
					<li><a href="#">Zarządzaj kontem</a></li>
					<li class="divider"></li>
					<li><a href="?action=logout">Wyloguj się</a></li>
				</ul>
			</li>
		</ul>
	</div>
</nav>