<?php
/**
 * Nadrzędna nawigacja, która wyświetlana jest w każdym szablonie.
 * Odseparowanie nawigacji pozwala na zastosowanie zasady DRY (Don't Repeat Yourself).
 * W nawigacji dostępna jest zmienna $settings z globalną konfiguracją systemu.
 */
?>
<nav class="navbar navbar-default navbar-inverse navbar-top-fixed">
	<div class="container">
		<div class="navbar-header">
			<a href="index.php" class="navbar-brand" title="Centrum Kontroli Lotów">
				<?php echo $site_title ?>
			</a>
		</div>

		<ul class="nav navbar-nav">
			<li class="dropdown">
				<a href="?controller=plane" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
					Samoloty <span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li class="dropdown-header" role="presentation">Samoloty</li>
					<li><a href="?controller=plane">Zarządzaj samolotami</a></li>
					<li><a href="?controller=plane&amp;action=add">Dodaj nowy</a></li>
					<li class="divider"></li>
					<li class="dropdown-header" role="presentation">Producenci</li>
					<li><a href="?controller=brand">Zarządzaj producentami</a></li>
					<li><a href="?controller=brand&amp;action=add">Dodaj nowego</a></li>
				</ul>
			</li>

			<li class="dropdown">
				<a href="?controller=user" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
					Użytkownicy <span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="?controller=user">Zarządzaj wszystkimi</a></li>
					<li><a href="?controller=user&amp;action=add">Dodaj nowego</a></li>
				</ul>
			</li>

			<li class="dropdown">
				<a href="?controller=plane" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
					Lokalizacje <span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li class="dropdown-header" role="presentation">Państwa</li>
					<li><a href="?controller=country">Zarządzaj państwami</a></li>
					<li><a href="?controller=country&amp;action=add">Dodaj nowe</a></li>
					<li class="divider"></li>
					<li class="dropdown-header" role="presentation">Miasta</li>
					<li><a href="?controller=city&amp;">Zarządzaj miastami</a></li>
					<li><a href="?controller=city&amp;action=add">Dodaj nowe</a></li>
				</ul>
			</li>
		</ul>

		<ul class="nav navbar-nav pull-right">
			<li>
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
					Piotr Filipek <span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#">Edytuj profil</a></li>
					<li><a href="#">Zarządzaj kontem</a></li>
					<li class="divider"></li>
					<li><a href="?action=logout">Wyloguj się</a></li>
				</ul>
			</li>
		</ul>
	</div>
</nav>